<a href="https://colab.research.google.com/github/SHIVA-RAMALINGAM/MachineLearningPractice/blob/main/Numpy_(Lecture).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
from time import process_time

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in range(10000)]


end_time = process_time()

print(end_time - start_time)

0.0014410030000000518


In [5]:
np_array = np.array([i for i in range(100070)])

start_time = process_time()

np_array = np_array+5;


end_time = process_time()

print(end_time-start_time)

0.0007729770000004521


In [14]:
a = np.array([(1,2,3,4,5),(6,7,8,9,10)])



print(a)
type(a)

a.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [11]:
list1 = np.array([1,2,3,4,5])
print(list1)

list1.shape

[1 2 3 4 5]


(5,)

In [17]:
c = np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype=float)

print(c)






[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [18]:
# create numpy array of zeros

x = np.zeros((2,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
#create a numy array of ones

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
#create an array of particular value
z = np.full((3,3),9)
print(z)


[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [22]:
#create an identity matrix - diagonals elements -1 other elements 0

a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [27]:
# create an numpy array with random values

b = np.random.random((3,3))
print(b)

[[0.79612358 0.23089577 0.84357678]
 [0.81562309 0.08954817 0.63448431]
 [0.15977875 0.35787135 0.42345477]]


In [29]:
# create random integer value array  within a specific range

c = np.random.randint(5,70,(3,4))
print(c)

[[54 21 45 28]
 [48 46 62 36]
 [ 6 51 40 51]]


In [31]:
# create an array of evenly spaced values

d = np.linspace(10,50,5)
print(d)

[10. 20. 30. 40. 50.]


In [32]:
# array of evenly spaced valued specifiying the step size

e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [34]:
#convert a list to a numpy array

list1 = [1,2,3,4,5]

np_array = np.asarray(list1)

print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Analysing a numpy array

In [35]:
 c = np.random.randint(10,90,(5,5))

 print(c)

[[43 10 54 18 86]
 [20 72 24 28 26]
 [19 69 83 47 45]
 [79 30 88 69 52]
 [55 21 83 60 80]]


In [36]:
#no of dimensions

print(c.ndim)

2


In [37]:
#array dimensions

print(c.shape)

(5, 5)


In [38]:
#number of elements in an array

print(c.size)

25


In [39]:
# checking datatype of values in an array

print(c.dtype)

int64


Mathematical operations on an numpy array


In [40]:
list1 = [1,2,3,4,5]

list2 = [6,7,8,9,10]

print(list1+list2) #concatenate or join two list / it does not add individual element addition like 1+6 2+7. ........

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [41]:
np_array1 = np.random.randint(10,50,(4,4))

np_array2 = np.random.randint(60,100,(4,4))


print(np_array1)

print(np_array2)


[[20 22 28 28]
 [29 45 37 29]
 [28 19 17 39]
 [21 19 14 15]]
[[89 79 87 71]
 [86 75 61 84]
 [70 97 83 75]
 [76 89 90 82]]


In [43]:
print(np_array1 + np_array2)


print(np_array1 - np_array2)

print(np_array1 * np_array2)

print(np_array1 / np_array2)

[[109 101 115  99]
 [115 120  98 113]
 [ 98 116 100 114]
 [ 97 108 104  97]]
[[-69 -57 -59 -43]
 [-57 -30 -24 -55]
 [-42 -78 -66 -36]
 [-55 -70 -76 -67]]
[[1780 1738 2436 1988]
 [2494 3375 2257 2436]
 [1960 1843 1411 2925]
 [1596 1691 1260 1230]]
[[0.2247191  0.27848101 0.32183908 0.3943662 ]
 [0.3372093  0.6        0.60655738 0.3452381 ]
 [0.4        0.19587629 0.20481928 0.52      ]
 [0.27631579 0.21348315 0.15555556 0.18292683]]


In [44]:
print(np.add(np_array1,np_array2))


print(np.subtract(np_array1,np_array2))


print(np.multiply(np_array1,np_array2))


print(np.divide(np_array1,np_array2))

[[109 101 115  99]
 [115 120  98 113]
 [ 98 116 100 114]
 [ 97 108 104  97]]
[[-69 -57 -59 -43]
 [-57 -30 -24 -55]
 [-42 -78 -66 -36]
 [-55 -70 -76 -67]]
[[1780 1738 2436 1988]
 [2494 3375 2257 2436]
 [1960 1843 1411 2925]
 [1596 1691 1260 1230]]
[[0.2247191  0.27848101 0.32183908 0.3943662 ]
 [0.3372093  0.6        0.60655738 0.3452381 ]
 [0.4        0.19587629 0.20481928 0.52      ]
 [0.27631579 0.21348315 0.15555556 0.18292683]]


Array Manipulation


In [ ]:
a = np.random.randint(1,10,(3,3))

print(a)